sources:
  - name: TheCatApi
    handler:
      openapi:
        source: ./schema.yml
  - name: CatDBApi
    handler:
      openapi:
        source: ./cat-api-schema.json
        endpoint: http://localhost:3333/api
transforms:
  - namingConvention:
      typeNames: pascalCase
      fieldNames: camelCase
